---
fixtures:
    repositories:
        stdlib:
            ref: "4.12.0"
            repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
        mysql:
            ref: "3.8.0"
            repo: "http://github.com/puppetlabs/puppetlabs-mysql"
        staging:
            ref: "v2.0.1"
            repo: "https://github.com/voxpupuli/puppet-staging"
        apache:
            ref: "1.10.0"
            repo: "https://github.com/puppetlabs/puppetlabs-apache"
        concat:
            ref: "2.2.0"
            repo: "https://github.com/puppetlabs/puppetlabs-concat"

    symlinks:
        limesurvey: '#{source_dir}'
